import {
  FitReportSchema,
  REPORT_SCHEMA_VERSION,
  type FitReport,
} from "@kol-fit/shared";

// Builds a valid FitReport (validated against FitReportSchema) that is
// unmistakably a placeholder. This is skeleton scaffolding — Unit 13 replaces
// the "build placeholder -> save" step with the real analysis pipeline's
// validated report.
export function buildPlaceholderReport(): FitReport {
  const report: FitReport = {
    schemaVersion: REPORT_SCHEMA_VERSION,
    overallScore: {
      value: 0,
      confidence: "low",
      reasons: ["Placeholder report — no analysis was performed."],
    },
    verdict: "OKAY",
    confidence: "low",
    evidence: {
      sampleSizes: {},
      notes: [
        "PLACEHOLDER report generated by the Unit 07 worker skeleton. No TwitterAPI.io, LLM, or scoring was run.",
      ],
    },
    bestUseCases: [],
    weakUseCases: [],
  };

  // Validate before it can be persisted (Invariant 12).
  return FitReportSchema.parse(report);
}
