import {
  AudienceClassificationSchema,
  ContentFitAssessmentSchema,
  FitReportSchema,
  KolContentClassificationSchema,
  OrgClassificationSchema,
  REPORT_SCHEMA_VERSION,
  type AudienceClassification,
  type ContentFitAssessment,
  type FitReport,
  type KolContentClassification,
  type OrgClassification,
  type ScoreMetric,
  type ScoreValue,
} from "@kol-fit/shared";

import type {
  AssessContentFitInput,
  ClassifyAudienceInput,
  ClassifyKolContentInput,
  ClassifyOrgInput,
  GenerateFitReportInput,
  LlmProvider,
} from "../provider.js";
import {
  assessContentFitMock,
  buildDistribution,
  extractKolContent,
  inferOrgClassification,
  toAudienceAccount,
} from "./classify.js";

const MOCK_MODEL_FALLBACK = "mock";

/**
 * Deterministic, network-free LLM provider. Same inputs always yield deep-equal
 * outputs. It classifies and writes synthetic narrative but never computes
 * numeric scores — those are passed through from input (Unit 14 scoring) or, if
 * absent, emitted as clearly-marked placeholders. Every output is validated
 * against its shared schema before being returned (Invariant 12).
 */
export class MockLlmProvider implements LlmProvider {
  readonly model: string;

  constructor(model?: string) {
    this.model = model && model.length > 0 ? model : MOCK_MODEL_FALLBACK;
  }

  async classifyOrgProfile(
    input: ClassifyOrgInput
  ): Promise<OrgClassification> {
    return OrgClassificationSchema.parse(inferOrgClassification(input));
  }

  async classifyKolContent(
    input: ClassifyKolContentInput
  ): Promise<KolContentClassification> {
    return KolContentClassificationSchema.parse(
      extractKolContent(input.posts, input.replies)
    );
  }

  async classifyAudienceAccounts(
    input: ClassifyAudienceInput
  ): Promise<AudienceClassification> {
    const accounts = input.accounts.map(toAudienceAccount);
    const distribution = buildDistribution(accounts);
    return AudienceClassificationSchema.parse({ accounts, distribution });
  }

  async assessContentFit(
    input: AssessContentFitInput
  ): Promise<ContentFitAssessment> {
    return ContentFitAssessmentSchema.parse(
      assessContentFitMock(
        input.org.classification,
        input.kol.content,
        input.org.handle,
        input.kol.profile
      )
    );
  }

  async generateFitReport(input: GenerateFitReportInput): Promise<FitReport> {
    const hasScores = Boolean(input.scores);

    const placeholder = (metric: string): ScoreValue => ({
      value: 0,
      confidence: "low",
      reasons: [`Placeholder for ${metric}; deterministic scoring runs in Unit 14.`],
    });
    const component = (metric: ScoreMetric): ScoreValue =>
      input.scores?.components?.[metric] ?? placeholder(metric);

    const overallScore = input.scores?.overall ?? placeholder("overall_fit");
    const verdict = input.verdict ?? "OKAY";
    const distribution = input.audience.distribution;

    // Deterministic top bucket for narrative flavor.
    const topBucket = Object.entries(distribution.buckets).sort(
      (a, b) => (b[1]?.count ?? 0) - (a[1]?.count ?? 0)
    )[0]?.[0];

    const verdictPhrase: Record<string, string> = {
      STRONG: "a strong fit",
      GOOD: "a good fit",
      OKAY: "a moderate fit",
      WEAK: "a weak fit",
      AVOID: "a poor fit",
    };
    const themes = input.kol.content.themes.join(", ") || "general crypto topics";
    const summary =
      `${input.kol.handle} looks like ${verdictPhrase[verdict] ?? "an uncertain fit"} for ` +
      `${input.org.handle}. Its content centers on ${themes}, and the engaged audience ` +
      `${topBucket ? `skews toward ${topBucket}` : "could not be characterised from the sample"}, ` +
      `which drives the overall assessment. ` +
      `${
        verdict === "STRONG" || verdict === "GOOD"
          ? "The audience overlap supports running a campaign here, with the recommended angle below."
          : "Weigh the weak use cases and risk sections below before committing budget."
      }`;

    const keyTakeaways = [
      `${input.kol.handle} is ${verdictPhrase[verdict] ?? "an uncertain fit"} for ${input.org.handle}.`,
      topBucket
        ? `The engaged audience skews toward ${topBucket}.`
        : "No engaged audience could be characterised from the sample.",
      `Content centers on ${themes}.`,
      input.kol.content.promoPatterns.length > 0
        ? "Promotional patterns detected — weigh brand/compliance risk."
        : "No strong paid-promo patterns detected.",
    ];

    const report: FitReport = {
      schemaVersion: REPORT_SCHEMA_VERSION,
      overallScore,
      verdict,
      confidence: input.scores?.confidence ?? "low",
      summary,
      keyTakeaways,
      evidence: {
        sampleSizes: input.sampleSizes ?? {
          engagedAccounts: distribution.sampleSize,
        },
        notes: [
          "Generated by the mock LLM provider (Unit 11); narrative is synthetic.",
          ...(hasScores
            ? []
            : [
                "Numeric scores are placeholders pending deterministic scoring (Unit 14).",
              ]),
        ],
      },
      bestUseCases: [
        `Reaching ${input.org.handle}'s audience via ${input.kol.handle}`,
        "Awareness among an engaged crypto-native audience",
      ],
      weakUseCases: ["Campaigns needing non-crypto reach"],
      audienceMatch: {
        summary: topBucket
          ? `The engaged audience skews toward ${topBucket}.`
          : "No engaged accounts were sampled.",
        score: component("engaged_audience_match"),
      },
      audienceBreakdown: distribution,
      contentAnalysis: {
        classification: input.kol.content,
        narrative: `Content centers on ${
          input.kol.content.themes.join(", ") || "general crypto topics"
        }.`,
      },
      engagementQuality: {
        narrative: "Engagement quality is estimated from sampled accounts.",
        signals: input.kol.content.promoPatterns,
      },
      paidPromo: {
        narrative:
          input.kol.content.promoPatterns.length > 0
            ? "Some promotional patterns detected."
            : "No strong paid-promo patterns detected.",
        riskScore: component("paid_promo_risk"),
      },
      botFarmRisk: {
        narrative: "Bot/farm risk is estimated from engaged-account signals.",
        riskScore: component("bot_farm_risk"),
      },
      brandSafety: {
        narrative: "Brand-safety assessment based on content and audience.",
        score: component("brand_safety"),
      },
      geoLanguageFit: {
        narrative: `Geo/language fit vs ${input.org.classification.region ?? "target region"}.`,
        score: component("geo_language_fit"),
      },
      recommendedAngle: `Position ${input.org.handle} to ${input.kol.handle}'s engaged audience.`,
    };

    return FitReportSchema.parse(report);
  }
}

export function createMockLlmProvider(options?: {
  model?: string;
}): MockLlmProvider {
  return new MockLlmProvider(options?.model);
}
