import {
  REPORT_SCHEMA_VERSION,
  type AudienceAccount,
  type AudienceBucket,
  type AudienceDistribution,
  type ScoreMetric,
  type ScoreValue,
} from "@kol-fit/shared";

import type { GenerateFitReportInput } from "../provider.js";

type Raw = Record<string, unknown>;

/** Recursively convert JSON `null` (strict-mode optionals) to `undefined`. */
export function deepNullToUndefined(value: unknown): unknown {
  if (value === null) return undefined;
  if (Array.isArray(value)) return value.map(deepNullToUndefined);
  if (value && typeof value === "object") {
    const out: Raw = {};
    for (const [k, v] of Object.entries(value as Raw)) out[k] = deepNullToUndefined(v);
    return out;
  }
  return value;
}

/** Deterministic per-bucket distribution over classified accounts. */
export function buildAudienceDistribution(
  accounts: AudienceAccount[]
): AudienceDistribution {
  const sampleSize = accounts.length;
  const counts = new Map<AudienceBucket, number>();
  for (const a of accounts) counts.set(a.bucket, (counts.get(a.bucket) ?? 0) + 1);
  const buckets: AudienceDistribution["buckets"] = {};
  for (const [bucket, count] of counts) {
    buckets[bucket] = { count, share: sampleSize === 0 ? 0 : count / sampleSize };
  }
  return { sampleSize, buckets };
}

/**
 * Assemble a FitReport from the model's narrative + the deterministic inputs.
 * Every numeric/score/verdict field comes from `input` — never the model.
 */
export function assembleFitReport(
  narrative: Raw,
  input: GenerateFitReportInput
): unknown {
  const placeholder = (metric: string): ScoreValue => ({
    value: 0,
    confidence: "low",
    reasons: [`No deterministic score available for ${metric}.`],
  });
  const component = (metric: ScoreMetric): ScoreValue =>
    input.scores?.components?.[metric] ?? placeholder(metric);

  const str = (v: unknown): string => (typeof v === "string" ? v : "");
  const arr = (v: unknown): string[] =>
    Array.isArray(v) ? v.filter((x): x is string => typeof x === "string") : [];

  return {
    schemaVersion: REPORT_SCHEMA_VERSION,
    overallScore: input.scores?.overall ?? placeholder("overall_fit"),
    verdict: input.verdict ?? "OKAY",
    confidence: input.scores?.confidence ?? "low",
    summary: str(narrative.summary) || undefined,
    keyTakeaways: arr(narrative.keyTakeaways),
    evidence: {
      sampleSizes:
        input.sampleSizes ?? { engagedAccounts: input.audience.distribution.sampleSize },
      notes: [
        "Narrative generated by the OpenAI provider; numeric scores are deterministic (packages/scoring).",
        ...arr(narrative.evidenceNotes),
      ],
    },
    bestUseCases: arr(narrative.bestUseCases),
    weakUseCases: arr(narrative.weakUseCases),
    audienceMatch: {
      summary: str(narrative.audienceMatchSummary),
      score: component("engaged_audience_match"),
    },
    audienceBreakdown: input.audience.distribution,
    contentAnalysis: {
      classification: input.kol.content,
      narrative: str(narrative.contentNarrative),
    },
    engagementQuality: {
      narrative: str(narrative.engagementNarrative),
      signals: arr(narrative.engagementSignals),
    },
    paidPromo: {
      narrative: str(narrative.paidPromoNarrative),
      riskScore: component("paid_promo_risk"),
    },
    botFarmRisk: {
      narrative: str(narrative.botFarmNarrative),
      riskScore: component("bot_farm_risk"),
    },
    brandSafety: {
      narrative: str(narrative.brandSafetyNarrative),
      score: component("brand_safety"),
    },
    geoLanguageFit: {
      narrative: str(narrative.geoNarrative),
      score: component("geo_language_fit"),
    },
    recommendedAngle: str(narrative.recommendedAngle),
  };
}
